### ISSUE TITLE
[Bug]: inquirer.prompt is not a function

### ISSUE THREAD

**Issue by sinlov** [bridgewwater/git-tidier#100]
### Component

cli

### Describe the bug

```
TypeError: inquirer.prompt is not a function
    at pipe (/usr/local/lib/node_modules/git-tidier/src/interact.js:24:12)
    at interactClear (/usr/local/lib/node_modules/git-tidier/src/interact.js:48:3)
    at Command.<anonymous> (/usr/local/lib/node_modules/git-tidier/bin/git-tidier.js:62:9)
```

### System Info

```shell
ProductName:            macOS
ProductVersion:         14.5
BuildVersion:           23F7
```

### Validations

- [X] Read the [Contributing Guidelines](../blob/main/.github/CONTRIBUTING_DOC/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](../issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already.

**Comment by sinlov** [comment]
for [github.com/SBoudrias/Inquirer.js/issues/606](https://github.com/SBoudrias/Inquirer.js/issues/606#issuecomment-1664647853)

- Use Inquirer v8 which is still CJS compatible (latest v9 is not)
- Use the new packages who are CJS compatible too See [https://github.com/SBoudrias/Inquirer.js/discussions/1214](https://github.com/SBoudrias/Inquirer.js/discussions/1214)

**Comment by sinlov** [comment]
for [github.com/SBoudrias/Inquirer.js/issues/606](https://github.com/SBoudrias/Inquirer.js/issues/606#issuecomment-1664647853)

- Use Inquirer v8 which is still CJS compatible (latest v9 is not)
- Use the new packages who are CJS compatible too See [https://github.com/SBoudrias/Inquirer.js/discussions/1214](https://github.com/SBoudrias/Inquirer.js/discussions/1214)

**Comment by Codehouze** [comment]
@sinlov Thank. This "inquirer": "8.2.4" worked for me.
